// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zowwqcnqdzqvgbguqrex.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Inpvd3dxY25xZHpxdmdiZ3VxcmV4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NjA4NTQsImV4cCI6MjA2MDIzNjg1NH0._hgKUmm7hGx-lQ4UWnw2ydseDZPjprJ-Lof5zS89Fpg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);